### ISSUE TITLE
configuration publishing doesn't work

### ISSUE THREAD

**Issue by larsbo** [FetchLeo/laravel-xml#1]
Hi,
great work so far!  👍 

But I can't publish the default config. When I run 
```
php artisan vendor:publish --provider=FetchLeo\LaravelXml\XmlServiceProvider
```
it just responses with `Nothing to publish for tag []` and no new config file has been written to `app/config`.

I solved this for the time being by copied the file manually from vendor folder. Thus this is just an info for you :)

Laravel version: 5.3.24

**Comment by FetchLeo** [comment]
Did you register the provider in your `config/app.php`? 

Also, this package isn't exactly updated and fully functional. I'll probably update it when I get the chance to do it.

Thanks for using it, though! 👍

**Comment by larsbo** [comment]
Yes, the provider is registered. I already converted some data to xml.

Now i wanted to create my own converter because i want to add attributes to xml elements. That's why I needed the config file.

**Comment by FetchLeo** [comment]
Hmm. I'll look into this; thanks for reporting.

**Comment by FetchLeo** [comment]
Hey @larsbo, try updating the package. You may need to run `composer update --prefer-source` in order for Composer to update. After doing that, run `php artisan vendor:publish --tag=laravel-xml`.

I hope there aren't any more issues! Please note that some features are not complete, and some configuration keys are not used at all (yet.)

Thanks for using my package! 👍

**Comment by larsbo** [comment]
Thank you for the quick update!
I can confirm that it works fine now :)

**Comment by FetchLeo** [comment]
👍
