### ISSUE TITLE
Not working with Illuminate\Database\Eloquent\Collection

### ISSUE THREAD

**Issue by ghost** [FetchLeo/laravel-xml#3]
After install this package i try convert EloquentCollection and get error Class 'FetchLeo\LaravelXml\Converters\Xml' not found.
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'FetchLeo\LaravelXml\Converters\Xml' not found in /home/scalderdom/Projects/3RUMM/vendor/fetchleo/laravel-xml/src/FetchLeo/LaravelXml/Converters/ArrayConverter.php:76
laravel 5.2

**Comment by FetchLeo** [comment]
Uh oh, that's not good. To fix that, add 
```php
use FetchLeo\LaravelXml\Facades\Xml;
```
before the class declaration in ArrayConverter.php.

I'll have a fix for this out later. Let me know if you have any more issues.

**Comment by ghost** [comment]
Thanks, i fix issue in this way in my project, but i want to inform about this issue.

**Comment by FetchLeo** [comment]
Fixed, sorry for the delay
